### ISSUE TITLE
not work 1.19.4

### ISSUE THREAD

**Issue by jeffl1ma** [yezhiyi9670/occlusion-culling-fix-sodium#1]
help fix 1.19,4

**Comment by yezhiyi9670** [comment]
Could you provide more specific info about your issue? I tested the released jar on 1.19.4 and it worked fine.

**Comment by yezhiyi9670** [comment]
The new release is now marked to support 1.19.4. See [Modrinth](https://modrinth.com/mod/occlusion-culling-fix-sodium/versions).

**Comment by jeffl1ma** [comment]
![image](https://github.com/yezhiyi9670/occlusion-culling-fix-sodium/assets/106811319/46da48b4-c1ba-48a9-b406-fe9f7e22f7c2)

**Comment by yezhiyi9670** [comment]
This may not be the same issue. I need your world seed and F3 screenshot to find what was wrong.

**Comment by jeffl1ma** [comment]
Sorry for the delay, but your mod is working perfectly, even tested in version 1.20, thanks for that, I don't know why sodium doesn't solve this, thanks to you I can play using sodium with good performance, thanks
