### ISSUE TITLE
rubidium version (forge)

### ISSUE THREAD

**Issue by benjaminkitson** [yezhiyi9670/occlusion-culling-fix-sodium#2]
I know asking about forge version of fabric mods often doesn't go down well, but given how small of a change this makes I thought I'd ask - how plausible would it be to implement this exact change but for forge? Cheers

**Comment by yezhiyi9670** [comment]
You mean Forge version of [this mod](https://modrinth.com/mod/occlusion-culling-fix-sodium)? The technical details should be exacly same, but I don't have much free time to do that. Maybe later.

**Comment by benjaminkitson** [comment]
yeah that's the one - okay, no worries, having the issue fixed so seamlessly in sodium and then finding it again in rubidium is infuriating 😂 cheers for the original mod though! I'd love to see it in forge, but yeah i get not having much free time, thanks for the quick response 👍

**Comment by yezhiyi9670** [comment]
Forge version (for 1.18+) is now released. See [Modrinth](https://modrinth.com/mod/occlusion-culling-fix-sodium/versions).

**Comment by benjaminkitson** [comment]
Oh wow, that's awesome! Might be worth noting it's for forge ports of sodium like rubidium rather than sodium itself, but that's super cool, thanks so much mate
