### ISSUE TITLE
If used with Sodium 0.5.0, it crashes.

### ISSUE THREAD

**Issue by J4PC** [yezhiyi9670/occlusion-culling-fix-sodium#3]
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot read field "field_44912" because "this.field_4015.field_1724" is null

![image](https://github.com/yezhiyi9670/occlusion-culling-fix-sodium/assets/97805057/504ceff2-5a8a-4f56-a1ec-acc4c9e2c620)
[crash-2023-08-06_10.09.51-client.txt](https://github.com/yezhiyi9670/occlusion-culling-fix-sodium/files/12268941/crash-2023-08-06_10.09.51-client.txt)

### Mods used:
fabric-api-0.86.1+1.20.1
sodium-fabric-mc1.20.1-0.5.0
ocrenderfix_sodium-fabric-1.2.0

**Comment by yezhiyi9670** [comment]
Sodium 5.0 should have fixed the bug itself, so this mod is no longer needed.
